name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - id: install-deps
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: build
        name: Build library
        run: yarn build

      - id: upload-artifact
        name: Upload release candidate
        uses: actions/upload-artifact@v3
        with:
          name: release-candidate
          path: ./dist/