name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - id: install-deps
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: build
        name: Build library
        run: yarn build

      - id: upload-artifact
        name: Upload release candidate
        uses: actions/upload-artifact@v3
        with:
          name: release-candidate
          path: ./dist/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: branch
        name: Get current branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch."

      - id: vet
        name: Verify default branch
        if: ${{ steps.branch.outputs.branch != github.event.repository.default_branch }}
        run: |
          echo "'${{ steps.branch.outputs.branch }}' is not the default branch of '${{ github.event.repository.default_branch }}'"
          exit 1

      - id: setup-node
        name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@palewire'

      - id: install-deps
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: build
        name: Build distribution
        run: yarn build

      - id: version
        name: Version
        run: npm version ${{ github.ref_name }} --no-git-tag-version

      - id: publish
        name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - id: commit
        name: Commit to default branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git status
          git add package.json
          git commit -m "Updated package.json version to ${{ github.ref_name }}"
          git checkout ${{ github.event.repository.default_branch }}
          git push origin ${{ github.event.repository.default_branch }}